# Generated by Django 6.0.4 on 2026-04-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
